### PR TITLE
bugfix: tx vertification failed when put after delete 

### LINKED ISSUE #1042: RESET_INVALID_ERROR found, after clear the table records, and add a record .
**Brief of the issue**
RESET_INVALID_ERROR found, after scan del table records, and add a record . 

**Your environment**
OS: ubuntu 16.04
xuperchain : master-2d08ff1 2021-03-09-09:47:21
gcc : gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
wasm contract

**Repo steps**
1. make a table, and add some table records
2. del all table records with scan operate. (clear the table records)
3. add a record into the table

**Expected behaviours**
add the record currectly .

**What actually happened**
RESET_INVALID_ERROR occur .

**Additional information**
with the sample code : https://github.com/myxchain/mytable/tree/address

### PR DESCRIPTION
**Pull request by chenfengjin**
## Description

What is the purpose of the change?
skip empty versioned data   when iterator over xmodel.  it fixes the tx vertification  failed bug when put after delete. see #1042  for more detailes

Fixes # (issue)
#1042 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Brief of your solution

Please describe your solution to solve the issue or feature request.

### CODE REVIEW

File: core/contract/bridge/syscall_service.go [hunk 1]
```diff
@@ -7,6 +7,7 @@ import (
 	"encoding/hex"
 	"errors"
 	"fmt"
+	"github.com/xuperchain/xuperchain/core/xmodel"
```
Comment (Tri-stone) [inline core/contract/bridge/syscall_service.go:10]: import三段式来引入，分别是原生包，引用的其他pkg，项目自己的pkg

**Review by Tri-stone — APPROVED** [review]
